### ISSUE TITLE
Where can I download the relevant test data

### ISSUE THREAD

**Issue by xbr2017** [AgilentGCMS/ssim-ghg-2024#1]
absco_data = load_absco_file(os.path.join(s.ABSCO_TABLE_FOLDER, "absco.h5"))
For example, how to get the "absco.h5" file and absco_ch4.hdf file?
Thank you so much!

**Comment by AgilentGCMS** [comment]
It's taking us longer to host the data than we anticipated, so [here's a stop-gap solution](https://gmao.gsfc.nasa.gov/gmaoftp/sourish/Colleagues/Geiser/ssim-ghg-data.tgz). We will update a README file with a more permanent location when we have that.

**Comment by AgilentGCMS** [comment]
Just realized that the tarball was missing some folders. I've uploaded a new tarball, please re-download from the same link.
